### ISSUE TITLE
Equipment that seem they should be swapped by Marshmallow rule but aren't

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#10]
- Gemstone, Burning Stick
- Oil Barrel, Nuclear Fridge
- Frost Shield, Flame Shield
- Short Gemstaff, Short Staff
- Fan the Frost, Fan the Flames
- Frozen Flute, Fireflash
- Angelfire, Angelfrost
- Flame Essence, Frost Essence
- Scorch, Hailstorm
- Magic Firewall, Magic Frostbolt

Also: Channel Rage doesn't have *any* swap

**Comment by JuniorUdale** [comment]
Thanks for this list, wouldn't have caught these otherwise ❤ Fixed!
