### ISSUE TITLE
Workaround to stop boxtech items triggering "on any equipment use" scripts multiple times

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#100]
This is iffy, but there might be one way around it. 

https://github.com/TerryCavanagh/diceydungeons.com/blob/master/src/elements/Equipment.hx#L2819

This is the part of the code that fires the on any equipment use scripts. It checks Rules for something (that I'm not sure is used anywhere?) - however, we can change that for a split second before the boxy equipment actually runs, then change it back after the boxy equipment activates.

Unfortunately, you can't change Rules in `on execute`, only `before execute`, so some shenanigans might be needed.

**Comment by TerryCavanagh** [comment]
Oh - is this issue over any of the v1.11 changes? Because ideally I wouldn't check in anything that breaks a working mod!

**Comment by JuniorUdale** [comment]
Oh no, this has nothing to do with 1.11 changes - this is just me getting down some notes on a janky thing I'm trying out. 1.11 hasn't broken anything, this is a long-standing issue on my end with the way I'm implementing some things.

**Comment by notmario** [comment]
You could use e.setvar to get Rules into `on execute`

**Comment by JuniorUdale** [comment]
This is a rabbit hole I can't be bothered to go down 😅 Closing!
