### ISSUE TITLE
Make sure to add specific changes for Magician's rule for "on X do Y" items

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#107]

**Comment by ncrecc** [comment]
Such as? Should probably do likewise for ncrmod

**Comment by JuniorUdale** [comment]
https://github.com/TerryCavanagh/diceydungeons.com/issues/2352

tl;dr: Any equipment with "on X do Y" like Hammer, Particle Accelerator, Lockpick - all should be prevented from being a countdown. Also *maybe* make them always accept X (so Hammer could never be made max5) but that's debatable

**Comment by JuniorUdale** [comment]
![image](https://user-images.githubusercontent.com/32357485/124393636-448a2580-dcf3-11eb-8575-558223163670.png)
phew! done! finally!
