### ISSUE TITLE
Many jinxes used a shortened form of the equipment name (or something completely irrelevant) as their name, which breaks form

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#12]
E.g. Message in a Bottle's jinx is "Message", Sunday Sundae (and Spice Cream Sundae)'s jinx is "Sundae", Explosive Shield's jinx is "Backfire" (a bit confusing since it has nothing to do with the Backfire equipment), Round of Applause's jinx is "Cursed".

Vanilla jinxes are exclusively named after whatever equipment grants them (except jinxes for breaking Lady Luck's commandments, for obvious reasons) and this should probably be reflected here - although thematic differences like Caps Lock's jinx being "cAPS lOCK" and Belated Delivery's jinx being "Delivery!" are fine

**Comment by JuniorUdale** [comment]
Yeah, disagree on this one - shortened forms for jinxes just "work", I feel. In vanilla, all the cases are:

- Slapsies, Concentration, Upkeep, Telephone, Mercy, Uncle (single word names so they work as jinxes)
- Arf Arf Arf (a funny, simple name, so works as a jinx)
- Broken Mirror ("curse next turn" would be too clunky so this works)
- Lady Luck's commandments (obvious reasons)

I think there's a bit of cleaning up I could do (and will do, keeping this open to remind me on), but I'm still keeping the shortened form for most of them.

**Comment by JuniorUdale** [comment]
Kinda done a basic cleanup, considering this a non-issue. Closing!
