### ISSUE TITLE
Essence rework

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#124]
Leave the effects as they are - "deal 4 damage", "inflict 1 burn" etc.
- [x] These effects now apply whenever the status is removed
- [x] Essences now remove themselves whenever 4 or more (of any essence, can mix + match these) have been inflicted
- [x] Essence Detonator now removes all essences on the enemy and deals 1 damage for each removed

**Comment by JackeeaJ** [comment]
all done! Just need to playtest this to see if it's balanced (and fun. lol).

**Comment by JackeeaJ** [comment]
Honestly, the new version didn't feel that fun. Going back to the old version where you need to use Essence Detonator, but it also returns the dice if the opponent didn't have any essences (letting you "cycle" it for free).
