### ISSUE TITLE
Consider scrapping or reworking Booster Pack

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#13]
It might've worked well in its original environment, but now that mod compatibility is heightened and it's more likely other items will show up aside it, issues will be abound when certain equipment interact with it:
- Hammerlikes' descriptions will be inaccurate (e.g. "on 6" equipment will require you to use a 5, since the 5 and the free1 sum to 6 - vanilla deals with this manually for cards like lament+ by checking if d == 7)
- split() isn't defined for numbers above 6
- An unrestricted Berlin Key-like would try to set a number to 7
- Some equipment, though it's rare, references how you always have 6 equipment (e.g. "do a thing to the equipment in the dth slot")

**Comment by JuniorUdale** [comment]
Hmm, you're probably right. I'll see if I can come up with a fix, though I might just scrap it at this point.

**Comment by JuniorUdale** [comment]
![image](https://user-images.githubusercontent.com/32357485/93668879-907f1d00-fa87-11ea-8a76-950d8daee783.png)
Done. Probably a bit boring, but it's better than breaking with other mods/magician/etc at least.
