### ISSUE TITLE
It's not immediately evident what Coconut Gun actually *does* the turn after you use it

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#130]
Countdown 8, "Deal 3 damage, reduce countdown to 3 this turn" 

I interpreted this to mean that if, for example, I put a 2 in the countdown after it was reduced to 3, then the countdown would be 6 next turn due to the inserted 2 last turn. I didn't realize until after using the item that that wasn't the case.

**Comment by JackeeaJ** [comment]
That makes sense - the countdown needs to reset *somehow* to stop it being a cd3 3 damage Pea Shooter, but resetting it all the way to 8 is probably a bit much. Now it'll take into consideration how much you reduced it by (so if you put a 2 into it, it'll reset to 6).
