### ISSUE TITLE
Remember to crossreference Reunion items to prevent name clashes

### ISSUE THREAD

**Issue by JackeeaJ** [JuniorUdale/MoreFluff#132]
e.g. i'm sure that you used Barbed Spear at some point

**Comment by TerryCavanagh** [comment]
as much as reasonably possible I'd like to avoid name clashes with mods, though inevitably there'll be a few things. Happy to have a go at renaming some stuff in Reunion if you give me a list of conflicts!

**Comment by TerryCavanagh** [comment]
Barbed Spear is one I'd really like to keep though! It's the literal translation for Gae Bolg 😅

**Comment by JackeeaJ** [comment]
> Barbed Spear is one I'd really like to keep though! It's the literal translation for Gae Bolg 😅

Exactly why I used it, but that's easily renamable on my end (better to have that name actually in the game!)

Having a quick check, it doesn't seem like there's any other clashes, which is pretty lucky! I'll leave this open for the time being since I'm sure there'll be items added for the other contestants.

**Comment by JackeeaJ** [comment]
Warrior introduces a clash with "Crunch", but that's something I can rename to Big Crunch (fits with the spacey theme of nearby items, lol)

**Comment by JackeeaJ** [comment]
3 more with the "final" reunion update:

- [ ] Crunch: should actually get around to renaming this to Big Crunch
- [ ] Metronome: could go with a Conductor pun. Maybe "Loud Conductor", that's weird enough to work
- [ ] Permafrost: there was *always* going to be a clash for this word somewhere, come on now lol. Just Permafrost@fluff will do, since I think collectively, every single cold-sounding noun has been used up somewhere

**Comment by JackeeaJ** [comment]
Fixed! Hopefully. maybe. probably!
