### ISSUE TITLE
Chilly Pepper and Chilly Pepper+ are the same thing

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#17]
![image](https://user-images.githubusercontent.com/11216597/93693013-2dfa4100-fac8-11ea-8a7c-7652979075e8.png)
Corporate needs you to find the differences between this picture and this picture.

**Comment by JuniorUdale** [comment]
Seems that part of the script for Chilly Pepper was different (it inflicted 2 freeze as it should), but the damage never went up, weird. Nice catch!
