### ISSUE TITLE
Magma Hurl gadget doesn't use magma's custom icon

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#24]
![image](https://user-images.githubusercontent.com/11216597/93830154-68391f00-fc3d-11ea-8fb3-4bf83e6ff6da.png)
Might be the same with the marshmallow swap equivalent

**Comment by JuniorUdale** [comment]
![image](https://user-images.githubusercontent.com/32357485/93837182-13b59400-fc7d-11ea-8f8c-a81d08430bcc.png)
Fixed!
