### ISSUE TITLE
Beam Power status and Beam Dream still have a cog icon in the description

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#26]
![image](https://user-images.githubusercontent.com/11216597/93959490-c988ed00-fd26-11ea-86cd-36e308224819.png)
![image](https://user-images.githubusercontent.com/11216597/93962928-ebd03a00-fd29-11ea-8d46-9524ca5654d2.png)

**Comment by JuniorUdale** [comment]
Fixed!
