### ISSUE TITLE
Stun Blast?, Stun Blast?-, and Stun Blast?+ have the same description but different effects

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#33]

**Comment by JuniorUdale** [comment]
These items aren't in More Fluff - are these from a different mod?

**Comment by ncrecc** [comment]
Crap, was doing some fire<>vanish fluff swaps and got some names confused. Meant Stun Blast?.

**Comment by JuniorUdale** [comment]
Fair enough, fixed!
