### ISSUE TITLE
List of items missing sfxdamage

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#35]
- Immolate+
- Ice Lash
- Cat o' Six Tails
- Heckfire
- Cryoshock
- Pyrodrop
- Snowdrop
- Hairdryer
- Breath Mints
- Channel Rage
- Channel Calm
- Faeblade
- Frozen Whip
- Overblaster
- Frost Fling
- Icy Blade of Iciness
- Firey Firesword of Fire

(also Ice Lash?- is different than Ice Lash- for some reason)

**Comment by JuniorUdale** [comment]
Fixed on all counts! (except Hairdryer and Breath Mints, which need tweaking anyway)
