### ISSUE TITLE
Consider nerfing Labrys

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#36]
As a Bonus Round starting weapon it's way too good - 12 damage in one turn for two 3s, essentially a slightly harder to use Very Good Sword. Battle Axe can do a maximum of 8 damage per turn for comparison. Could make it MAX2 upgrading to MAX3
(typing that out made me realize just how op kunai+ is as a size 1 reuseable :p)

**Comment by JuniorUdale** [comment]
Sorry, no - Labrys feels in a good spot to me. Decent item with a not so great upgrade, and I'm fine with some items being too strong as a starter. For reference, 2x Boxing Gloves gets you 10 damage in 1 turn, Boomerang and Small Shield get you 12 damage at the cost of anywhere from 3-6 health, Nail Bat is 9 damage and charges your limit... Labrys is on the more powerful end of the spectrum, but it feels balanced *enough*.

Plus, making it MAX2 would render it much too weak (same effect as Battle Axe, except needs two dice).
