### ISSUE TITLE
Remove redundant gadgets, maybe

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#37]
Goop Gun and Life Leech are both the same as the since-introduced vanilla gadgets Acid Arrow and Blood Sip. However, I'm not fully sure whether they should be removed or not, since they represent some of the mod's history: it's old enough that they predate vanilla gadgets

**Comment by TerryCavanagh** [comment]
(Fwiw, I think you should keep your gadgets!)

**Comment by JuniorUdale** [comment]
Yeah, I think I'm going to keep these, since it's nice to put my own "spin" on things.
