### ISSUE TITLE
Less Inventor equipment should scrap to Bubble Gun

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#4]
Bubble Gun seems to be used as a "todo: give these gadgets later" placeholder, and isn't very fun to come across when you scrap actually useful equipment:

Generous Sword
Dainsleif
Helium Balloon (could scrap to magic dice?)
Sarissa
Snail Bat
Bureaucratic Blade
Auto Turret
Baseball Bat
Slice and Dice (you could probably _merge some properties into the Inventor Gadgets card so bleed gadgets are doable)
Blunt Sword
Blunt Dagger
Fulcrum Blade
Reconstructificate
Staple Gun
Syringe Gun

Auto Turret may be disputable since doing an extra 1 damage per turn is really just a nerfed version of doing an extra 3 damage per turn, although Scrap Turret also scraps to Bubble Gun which is the same extra 1 damage per turn. Syringe Gun I only included because Blood Sip seems like an obvious gadget for it.

The gadget Grammar Fickses is also completely unused when it seems to be related to Plurale Tantrum, but I suppose Plurale scrapping to Grammar Fickses would just be the same joke repeated ad verbum (doesn't stop Swedge scrapping to Finger Guns or Scrap Remote scrapping to Broken Gadget though)

There's also some non-Inventor equipment for which Bubble Gun seems an odd choice of gadget, may be worth changing for the sake of Val/Yolanda rule or future generator overhauls:

Trebuchet
Jade Blade
Xiphos
Bang Snaps
Rusty Broadsword
Cherry Bomb
Splat
Critical Hit
Bayonet
Rose Bush
Sunder

**Comment by JuniorUdale** [comment]
I've given the gadgets a quick pass, and I agree with most of these suggestions. Fixed for the next update!
