### ISSUE TITLE
Call for Backup cards don't get properly replaced by Transmogrify

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#41]
![image](https://user-images.githubusercontent.com/11216597/95812900-83e79080-0ce4-11eb-98ca-5ef3f5632447.png)
This shows as "Fire Siphon" in the upcoming cards list, but when it actually arrives in the hand it's still just CfB Thief? but unpressable.
Try this: if self.layout == "DECK", instead of using eq.create, manually replace the associated Card object's equipment; e.g. Deck.getcards("all")[something].equipment = new elements.Equipment("something")

**Comment by JuniorUdale** [comment]
Oh, uff, I thought I'd fixed that :\ I thought I made a specific case to stop CfB cards from getting switched out! I'll try tinkering with it and see what I can do.

**Comment by JuniorUdale** [comment]
Fixed in a slightly roundabout way! You can do `eq.equipmentpanel.remove(); eq.equipmentpanel = null;` before `e.create()` to stop a CfB card from acting up.
