### ISSUE TITLE
Equipment attainable with Inventor through Yolanda rule (or a "get a random item" card) that lack a gadget

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#46]
* Flame Launch
* Frost Launch
* Frost Launch?
* Healing Song
* Reject
* Mana Cannon
* Pyrodrop
* Cryolily
* Wisteria
* Camellia
* Dogwood
* Lavender
* Marigold
* Twolip
* Pansy
* Pear Spear
* Swingset
* Carnation
* Magnolia
* Magic Mistletoe
* Crocus
* Coffee Bean
* April Showers
* Snowdrop
* Thermalily
* Blackberry
* Ginger
* Hydrangea
* Bloodroot
* Pea Pod

In addition, Marshsword, Glamour, Suspicious Box, Begonia, Iris, Rannuncarpus (despite its description referring to used equipment as "spells"), and I suppose the Essence items, though marked excludefromrandomlists, have no gadget despite theoretically working fine in Inventor's hands.

**Comment by JuniorUdale** [comment]
Done! I'm not adding a gadget to any unused items, or those marked `excludefromrandomlists` or e.g. `robotonly` - if you can get those as an item to gadgetize, good luck. 😅

**Comment by JuniorUdale** [comment]
FWIW, I've went back on that idea - now ALL equipment has a gadget. Not all of them are that relevant (most CPU-manipulating items give limit break charge/boost countdowns, but it's nice to be a bit more thorough.
