### ISSUE TITLE
Stun? does nothing

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#48]
![image](https://user-images.githubusercontent.com/11216597/97060296-e3edfa80-1560-11eb-8ff9-4924bc3677c5.png)

**Comment by JuniorUdale** [comment]
Huh, apparently I got halfway around to implementing Stun?, but now it just does `for(mydice in self.dicepool){trace(mydice.basevalue);};`. Weird! I'll get this fixed soon.

**Comment by JuniorUdale** [comment]
Fixed.
