### ISSUE TITLE
Small unimportant crap

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#5]
* Daydream_downgraded heals for 999 instead of 998, inconsistent with description
* Sunder_downgraded does sfxdamage for max instead of min
* sfxdamage is called twice in Green Dragon Blade
* Frost Fling_downgraded is reusable instead of standard one-use
* Icy Iceblade of Iciness_downgraded (and its ? equivalent) do fire damage/sfx instead of freeze damage/sfx
* Insult to injury should probably specify "gain an extra turn" rather than "take an extra turn"
* Essence Detonator?_upgraded and _downgraded have a different script than Essence Detonator?, and don't work with dark essence
* Blood to Dice_upgraded has a stray snippet in before execute related to helium balloon

**Comment by JuniorUdale** [comment]
Thanks for these reports! Should have them all fixed for the next patch.
