### ISSUE TITLE
Some Jester substitutions aren't working

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#50]
![image](https://user-images.githubusercontent.com/11216597/97061977-e05d7200-1566-11eb-8fc2-6c068cf31f12.png)
Starburst pack. I believe this happens with the Starburst and Transmogrify packs, but *not* the Eviscerate pack. May be a capitalization issue in dungeonchanges.hx?

**Comment by plasmaster09** [comment]
> Starburst pack. I believe this happens with the Starburst and Transmogrify packs, but _not_ the Eviscerate pack. May be a capitalization issue in dungeonchanges.hx?

If I know anything about Jester packs, it's capitalization. Capitalization is an absolute pain with custom packs for seemingly no reason.

**Comment by JuniorUdale** [comment]
Fixed! Hopefully. I think? Capitalized the `Boosterpack:` part of `dungeonchanges.hx` and that seems to have done the trick.
