### ISSUE TITLE
Issues with Magma? and Shiver?

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#55]
- [x] Likely crash due to #47 
- [x] "take [fire]2x\<value> damage" for Magma? description vs. "take 2x [ice]\<value> damage" for Shiver? description
- [x] Uses the standard fire & ice icons in their descriptions ("reduce how much [fire]Magma? you have by half", "reduce how much [ice]Shiver? you have by half")

**Comment by JuniorUdale** [comment]
reasons this had to be put off for almost a year: none. Fixed!
