### ISSUE TITLE
Spectre "Inflict 1 vanish" is wrong; vanilla vanish doesn't stack

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#56]
This is like saying "Inflict 1 confuse" or "Inflict 1 silence"

**Comment by ncrecc** [comment]
Or is this an ncrmod reference :thinking:

**Comment by JuniorUdale** [comment]
I think I must have had ncrmod on my mind when I did this 😅 I've been meaning to remove those items anyway tbh, will get around to that soonish

**Comment by ncrecc** [comment]
Remove Faeblade and Spectre? I think they're fine, vanish is roughly the same strength whether you inflict 1 of it or inflict standard "all" of it, If this is about the vanish<>fire swap project, I've already come up with a balanced-enough fire version of Faeblade; "on 6, instead [of doing damage], burn all dice"

**Comment by JuniorUdale** [comment]
Faeblade has been removed, Spectre's had its description updated to just say "Inflict Vanish". It isn't used in any normal items, but it's good to keep in case I want to give an OP gadget. (not Reversal levels of OP, but yeah)
