### ISSUE TITLE
itemcounter.py is a bit overgenerous

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#58]
- Includes all @ versions of an item with only @ versions (e.g. Precious Egg should just be counted once)
- Includes equipment with only _ versions, implying they're meant for items outside the mod (e.g. I added _deckupgrade versions to several vanilla items, and those were counted as unique items)
- There's a bug where if an item has only an @ version, like "Revolver@ncrmod" to prevent name clashes, it counts all the _ versions of that

ncrmod's nominal item count went from 631 to ~580 when I spotted these; might want to revise itemcounter if it's meant as a public resource
Here's a version with those changes made: 
[itemcounter.py.txt](https://github.com/JuniorUdale/MoreFluff/files/5473204/itemcounter.py.txt)

(This might mean Fluff doesn't "really" have 1000 items. Yep, I'm a buzzkill :P)

**Comment by JuniorUdale** [comment]
Thanks for this! 
![image](https://user-images.githubusercontent.com/32357485/101991159-d02e5d00-3ca2-11eb-8a37-056b4635eb77.png)
(Still over 1000... just about!)
