### ISSUE TITLE
Think about a rework to Zweihander

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#59]
Currently it's a bit unwieldy to use, as well as having a confusing description, as well as breaking with Magician. Just an all-round Not Good item. Think about reworking it at some point

**Comment by ncrecc** [comment]
> breaking with Magician.
Does \<slotdoubles> not preview anything unless both dice are the same? I don't see what's wrong with Zweihander that isn't wrong with any other value-dependent needs doubles item.

**Comment by JuniorUdale** [comment]
The thing is, Zweihander literally does 2x[] damage, so whatever the slots change to, it'll do double that amount of damage, which... isn't great, balance-wise. Plus the description is just `Deal [sword]2x<slotdoubles> damage` which looks a bit ugly.

**Comment by ncrecc** [comment]
When you wrote Magician, you ensured doubles equipment never changes to something that lets it have a potential value higher than 6, to prevent items like Skeleton Key and Memorise from bugging out. So at worst player gets a two-handed slightly stricter Battle Axe. Description is a little ugly but there's hacks like that all over the place in most mods, e.g. ``Do [sword]<d6> - 3[;] get dice - 3|[gray](Reusable)``

**Comment by JuniorUdale** [comment]
![image](https://user-images.githubusercontent.com/32357485/98293180-cc256600-1fa5-11eb-8179-a0341f02ff9a.png)
This feels much better. It was a little on the weak side anyway! The old design just felt... strange, and I'm happy with this reworked version. Pretty sure that a two handed sword with a conditional upside is... fine to give to Warrior and the like.
