### ISSUE TITLE
Remember to replace old "ignore re-equip" method with cannotreuse tag

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#6]
Currently the cards that ignore re-equip (Cauldron Cauldron, Reaper, Gift Box) do this: in before execute, assign getstatusself(REEQUIPNEXT) to a variable and remove all your re-equip. On execute, inflict re-equip on yourself equal to the aforementioned variable (and then reset that variable).

There's a cleaner way to do this that does not visually remove your re-equip (or cause the visual effect for when you get re-equip) and also doesn't trigger on alternate reequip: before execute, iterate through self.status for a status where x.type == "reequipnext", and copy x.value to a variable then set it to zero. On execute, look through self.status for "reequipnext" again and set its value to the aforementioned variable (and then reset the variable). May want to check if(self.status.length > 0) in the before execute script so it doesn't trace an error if you have no status effects.

I've actually confirmed that this works, unlike the last time I suggested an enhancement through obscure methods ("hey jackeea if you trace ICE it's 'ice' in normal mode and 'alternate_ice' in PU!!!")
![piercereeq](https://user-images.githubusercontent.com/11216597/73141639-67230400-4054-11ea-964b-0e6c46880875.gif)
(Tooltip text also works perfectly fine, that's not shown in the gif though)

Only snag is that this messes up if the ignore re-equip card in question was given by giveequipment, however that also happens with the getstatusself(REEQUIPNEXT) method and is a symptom of https://github.com/TerryCavanagh/diceydungeons.com/issues/1576

**Comment by ncrecc** [comment]
Oh hey cannotreuse exists now

**Comment by JuniorUdale** [comment]
Fixed! `cannotreuse` is on these items (that I didn't end up reworking anyway, lol)
