### ISSUE TITLE
Overheat is missing sfxdamage

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#66]
And probably its ice variant also.
Maybe somehow do a search for all cells that contain ``attack(`` or ``attackself(`` (excluding ``attackself(-``) but do *not* contain ``sfx(~_damage~``, ``sfx(~_takedamage~``, or ``sfxdamage(``.

**Comment by JuniorUdale** [comment]
Fixed! Also done a pass through the equipment, and added sound effects to all of them that "work". (Some equipment like Stun Blast, that plays multiple sound effects anyway, didn't really need it.)
