### ISSUE TITLE
Putting doubles into Differblade returns a 1

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#68]
![differblade](https://user-images.githubusercontent.com/11216597/100560856-218f2300-3285-11eb-9003-ffef2a501330.gif)
Or this might be a 0, but the console doesn't spam "dice can't have a value of 0, setting to 1" for this

**Comment by JuniorUdale** [comment]
I just spent 15 minutes trying to reproduce this, failing, then realizing "wait, I caught this on my end and fixed this a while ago, but haven't updated fluff yet" 😅 Thanks for the report though!

**Comment by ncrecc** [comment]
ahh, duh :P will make sure to check the github code next time 👍
