### ISSUE TITLE
PU status detection

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#7]
This could eliminate the need for items whose ? versions have identical descriptions but work differently under the hood, specifically Superbolt, Electric Fence, Icy Blade of Iciness, Splinters, Incapacitate, Stun Blast, Nitro Bump, and Shrapnel (which actually doesn't have one yet but would've needed one).
Talked about this a little on the discord but didn't really go into detail. statuses can be added to fighters other than self and target with fighter.addstatus(), allowing you to do this
```
var altshock = false;
var dummyfighter = new elements.Fighter(~Pirate~);
dummyfighter.addstatus(~shock~|1);
for(mystat in dummyfighter.status) {
    if(mystat.type == ~alternate_shock~) {
        altshock = true;
    }
}
if(altshock) e.animate(~alternate_shock~);
else e.animate(~shock~);
```
Pirate is a completely arbitrary enemy and can be replaced with any other enemy
Note: with addstatus you need to specify a number after the status name, I think it defaults to 0 otherwise
There's no way to manually remove fighters once they're created but I'm 90% sure that doesn't affect anything and they're automatically removed if you don't put them anywhere

**Comment by ncrecc** [comment]
Much, much, much saner way to do this. Put this in before combat:
```
if(Rules.alternatestatus.indexOf(~statusname~) != -1) { self.setvar(~statusisalt~|true); };
```
then check self.getvar(\~statusisalt\~)

**Comment by ncrecc** [comment]
Doubly sane way to do this, for real this time, that doesn't break for cards summoned mid-combat. Megaquest uses runscript to directly retrieve Rules; there's a getrules.hx script that just contains:
```
return Rules;
```
And instances of Rules where Rules isn't allowed to be accessed are just retrieved through running that script, e.g. ``runscript(~megaquest/getrules~).lowhpmusic = false;`` instead of ``Rules.lowhpmusic = false;`` for disabling the low HP music in the on execute column.

**Comment by JuniorUdale** [comment]
If it's this easy, then I'll try my best to get these fixes in for the next update (whenever I get around to doing that).

**Comment by JuniorUdale** [comment]
Fixed!
