### ISSUE TITLE
Rename Warhammer to Warhammer@morefluff

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#72]
Currently fluff's Warhammer is just in its equipment.csv, ncrmod has a lot more references to its Warhammer

**Comment by JuniorUdale** [comment]
Ah, will do! Are there any other equipment that it would be convenient to get tagged?

**Comment by ncrecc** [comment]
Just that and Scraptula. Revolver and Fissure were conflicts, but I tagged those @ncrmod already. Energy Drink conflicts with Megaquest, though.

**Comment by JuniorUdale** [comment]
Fixed Warhammer, but I'm not going to touch Energy Drink (for now) since Mystic is redoing MQ from scratch.
