### ISSUE TITLE
Repast Rapier could use a buff

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#73]
Right now it only heals 2 hp after battle so it's just venus fly trap but Not As Good

**Comment by JuniorUdale** [comment]
It has the added effect that if you're at maximum health *now*, but want to bank some extra healing for later, you totally can. Not as immediately useful as VFT for keeping your health always topped up, but it has its uses. I think it's fine in its current state to be honest; not *every* item has to be power creep on vanilla items!

**Comment by ncrecc** [comment]
Oh, makes sense
