### ISSUE TITLE
Skip Turn doesn't work

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#81]
it's... empty for some reason?

**Comment by ncrecc** [comment]
Skip Turn now crashes the game on start turn

**Comment by JuniorUdale** [comment]
Oh, hm. I've been trying to fiddle around with it, but at this point I might as well just get rid of it since it refuses to work properly. It's not used in that many items, so it's not *that* big of a loss.

**Comment by ncrecc** [comment]
Does just calling doendturnnow before start turn (or a frame or so after using an actuator) not work?

**Comment by JuniorUdale** [comment]
I'm pretty sure that calling it any time during the enemy's turn just... breaks things. I'll have a fiddle around with it though, not totally losing hope on this *quite* yet.

**Comment by JuniorUdale** [comment]
Kind of kludged around this for the time being:
* If it's given to the player, skip their turn ~0.1 seconds after it starts
* If it's given to the enemy, instead give the player a stacking Extra Turn status
Still needs some polish before I close this issue though.

**Comment by JuniorUdale** [comment]
Fiddled around, and it seems to be fine for now. However in doing so you've broken bonusturn (for enemies), ughhhhh

**Comment by JuniorUdale** [comment]
![image](https://user-images.githubusercontent.com/32357485/126081062-867fc4c7-d8de-49c9-bc1c-16f745d70dcb.png)

let me never have to touch this ever again
