### ISSUE TITLE
Refund only works for Jester, but is not marked excludefromrandomlists

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#85]
Making it work for other classes would be hilarious tbh, just check if self.layout != ('DECK') and if so, make it error all of your equipment and give dice they would use

**Comment by JuniorUdale** [comment]
Oh wow that's a beautifully cruel idea, I like it 😅

**Comment by JuniorUdale** [comment]
https://user-images.githubusercontent.com/32357485/106030144-c2536080-60c5-11eb-9923-983854fba6c2.mp4

Brilliant. Thanks for this idea!
