### ISSUE TITLE
Dainsleif refuses to kill Drake in PU

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#88]
Overzealous getstatus(VAMPIRE) check? (since vampire is automatically changed to alternate_vampire in the script when vampire is set to alternate)
If it is due to some vampire check, try checking that getstatus(VAMPIRE) > 0 && getstatus("alternate_vampire") == 0 instead. If vampire gets switched to alternate that would read "is alternate_vampire over zero and equal to zero" which is always false

**Comment by ncrecc** [comment]
Repro, if necessary: happened when Drake was at 2 max hp and at 1 max hp

**Comment by JuniorUdale** [comment]
Ah, good catch, thanks. Fixed!
