### ISSUE TITLE
Exoskeleton is entirely useless when shield is PU (e.g. Warlock rule)

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#90]
...what it *should* do in that case, I have no idea, best of luck to you :p

**Comment by JuniorUdale** [comment]
"Gain shield for the enemy's turn only" in the context of PU is... uh... damn. Honestly I should just make this give you the PU shield heal anyway, making this a bit OP (heal 2 health every turn except the first), but eh. At least you can't do Shield Bash shenanigans with it?

**Comment by ncrecc** [comment]
2 free shield each turn is about on par with Thick Skin, so this seems alright.

**Comment by JuniorUdale** [comment]
Fixed this, with the kludge of delaying the shield removal by 0.1 seconds. I am very confident that this will never ever come back to bite me in the backside, absolutely not.

(does cause an awkwardish visual twitch where Shield Down is removed slightly after Shield?, but this is simpler than the alternatives)
