### ISSUE TITLE
Whacksies jinx description does not display in sentence case when it applies

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#93]

**Comment by JuniorUdale** [comment]
Not sure what you mean here - this seems fine to me?
![image](https://user-images.githubusercontent.com/32357485/105985745-ccf50200-6093-11eb-86aa-9abba421bd82.png)
![image](https://user-images.githubusercontent.com/32357485/105985752-d1211f80-6093-11eb-9623-c467762b6a57.png)
Unless I've fixed this on my end

**Comment by ncrecc** [comment]
Fixed on your end, then. skills.csv on this repo still has the bug.

(Perhaps you should make a new commit soon :P)

**Comment by JuniorUdale** [comment]
That's a good point actually - still pretty far from publicly posting this patch, but keeping it up to date on here seems... useful.
