### ISSUE TITLE
Stun? can target Burnt? dice, making Stun Blast less effective in PU (burnt dice is instantly stunned)

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#96]

**Comment by ncrecc** [comment]
How I'd implement this is make Stun? *able* to target burnt/burnt? dice, but only do so if there are no unburnt/unburnt? dice to chose from

**Comment by JuniorUdale** [comment]
There's so many dice statuses, this ended up being weird and janky - now it just changes `self.bonusdice`, like how that one Halloween item did. Technically fixed!
